### ISSUE TITLE
No method 'find'

### ISSUE THREAD

**Issue by Palgie** [tj/co-monk#1]
Hi TJ,

Do you know why this might not work as expected?

Node Version : v0.11.9

Server.js

``` javascript
var koa = require('koa')
    , route = require('koa-route')
    , views = require('co-views')
    , app = module.exports = koa()
    , monk = require('monk')
    , wrap = require('co-monk')
    , db = monk('localhost/test')
    , users = wrap(db.get('users'));

var render = views(__dirname + '/app/templates', { map: { html: 'swig' }});
var users = {
      list: function *(){
        var out = yield users.find({});
        console.log(out);
        this.body = yield render('users', { users : out });
      }
    };

app.use(route.get('/users', users.list));

app.listen(3000);
console.log('listening on port 3000');
```

Package.json

``` json

{
  "name": "mpnode",
  "version": "0.0.1",
  "homepage":"http://mediapig.co.uk",
  "url": "https://github.com/Palgie/mpnode",
  "devDependencies": {
    "koa": "0.2.1",
    "koa-mount": "~1.2.3",
    "koa-static": "~1.4.2",
    "koa-route": "latest",
    "swig": "1.2.2",
    "underscore" : "1.5.2",
    "consolidate": "0.10.0",
    "co-views": "0.1.0",
    "mongodb": "1.3.10",
    "monk": "latest",
    "co-monk": "latest"
  }
}
```

Error

``` javascript
TypeError: Object #<Object> has no method 'find'
    at Object.users.list (/Users/gourleyp/Sites/mpnode/server.js:13:28)
    at GeneratorFunctionPrototype.next (native)
    at next (/Users/gourleyp/Sites/mpnode/node_modules/koa/node_modules/co/index.js:76:21)
    at Object.<anonymous> (/Users/gourleyp/Sites/mpnode/node_modules/koa/node_modules/co/index.js:56:5)
    at next (/Users/gourleyp/Sites/mpnode/node_modules/koa/node_modules/co/index.js:92:21)
    at Object.<anonymous> (/Users/gourleyp/Sites/mpnode/node_modules/koa/node_modules/co/index.js:56:5)
    at Server.<anonymous> (/Users/gourleyp/Sites/mpnode/node_modules/koa/lib/application.js:105:8)
    at Server.EventEmitter.emit (events.js:101:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:505:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
```

Apologies if this seems simple.

Seems to be related to running .find on the user table.

**Comment by tj** [comment]
looks ok at a glance

**Comment by haoxins** [comment]
you declared `users` twice

``` js
 , users = wrap(db.get('users'));
```

and

``` js
var users = {
```

**Comment by tj** [comment]
ah yes :D

**Comment by Palgie** [comment]
Well that's embarrassing!

Thanks for the help guys.
